CREATE DATABASE ForumCodeGym

CREATE TABLE ChuDe
(
	MaCD	INT				NOT NULL	PRIMARY KEY,
	TENCD	NVARCHAR(500)	NOT NULL
)

CREATE TABLE ThanhVien
(
	MATV	INT				NOT NULL	PRIMARY KEY,
	TENTV	NVARCHAR(200)	NOT NULL,
	MATMA	VARCHAR(20)		NOT NULL
)

CREATE TABLE BaiViet
(
	MABV			INT				NOT NULL	PRIMARY KEY,
	NOIDUNG			NVARCHAR(max)	NOT NULL,
	TIEUDE			NVARCHAR(500)	NOT NULL,
	MACD			INT				NOT NULL,	
	FOREIGN KEY (MACD) REFERENCES ChuDe(MACD),
	MATV			INT				NOT NULL,
	FOREIGN KEY (MATV) REFERENCES ThanhVien(MATV),
	ThaoLuan_MaBV	INT				NOT NULL,
	FOREIGN KEY (MABV) REFERENCES BaiViet(MABV),
)


INSERT INTO ThanhVien(MATV, TENTV, MATMA) VALUES(1,'Trong Nguyen','12345')
INSERT INTO ThanhVien(MATV, TENTV, MATMA) VALUES(2,'Diep Huy','12345')
INSERT INTO ThanhVien(MATV, TENTV, MATMA) VALUES(3,'Chinh','12345')
INSERT INTO ThanhVien(MATV, TENTV, MATMA) VALUES(4,'Long','12345')
INSERT INTO ThanhVien(MATV, TENTV, MATMA) VALUES(5,'Nam','12345')


SELECT * FROM ThanhVien

SELECT * FROM ThanhVien WHERE MATV = 2

SELECT * FROM ThanhVien WHERE MATV = 1 OR MATV = 2

SELECT * FROM ThanhVien WHERE MATV IN(1,3)

SELECT * FROM ThanhVien WHERE TENTV LIKE '%D%'

INSERT INTO ChuDe(MaCD,TENCD) VALUES (1,N'Văn')
INSERT INTO ChuDe(MaCD,TENCD) VALUES (2,N'Toán')
INSERT INTO ChuDe(MaCD,TENCD) VALUES (3,N'Lý')
INSERT INTO ChuDe(MaCD,TENCD) VALUES (4,N'Hóa')
INSERT INTO ChuDe(MaCD,TENCD) VALUES (5,N'Sinh')

SELECT * FROM ChuDe

INSERT INTO BaiViet(MABV,TIEUDE,NOIDUNG,MATV,MACD,ThaoLuan_MaBV)
VALUES(1,N'Giải phương trình bậc 2',N'Cách giải hương trình bậc 2',1,2,1)

INSERT INTO BaiViet(MABV,TIEUDE,NOIDUNG,MATV,MACD,ThaoLuan_MaBV)
VALUES(2,N'Giải phương trình bậc 2',N'Thảo luận 1 - cách giải phương trình bậc 2',3,2,1)

SELECT * FROM BaiViet

INSERT INTO BaiViet(MABV,TIEUDE,NOIDUNG,MATV,MACD,ThaoLuan_MaBV)
VALUES(3,N'Giải phương trình bậc 2',N'Cách giải hương trình bậc 2',5,2,1)

SELECT BV.MABV AS 'MA BAI VIET',BV.TIEUDE,BV.NOIDUNG,CD.TENCD,TV.TENTV
FROM BaiViet AS BV 
INNER JOIN ThanhVien AS TV ON BV.MATV = TV.MATV
INNER JOIN ChuDe AS CD ON BV.MACD = CD.MaCD

SELECT TV.MATV,TV.TENTV,MABV
FROM BaiViet BV INNER JOIN ThanhVien TV ON BV.MATV = TV.MATV
WHERE BV.ThaoLuan_MaBV = 1 AND BV.MABV <> 1

SELECT CD.MaCD,CD.TENCD,BV.MABV,BV.TIEUDE
FROM BaiViet BV INNER JOIN ChuDe CD ON BV.MACD = CD.MaCD
WHERE CD.TENCD = N'Toán'

