CREATE DATABASE NganHang

CREATE TABLE Customers
(
	CUSTOMER_NUMBER				INT				NOT NULL,
	FULLNAME					NVARCHAR(30)	NOT NULL,
	ADDRESS_CUS					NVARCHAR(50)	NOT NULL,
)

ALTER TABLE Customers ADD PRIMARY KEY (CUSTOMER_NUMBER)

CREATE TABLE ACCOUNT
(
	ACCOUNT_NUMBER				INT				NOT NULL PRIMARY KEY,
	ACCOUNT_TYPE				NVARCHAR(50)	NOT NULL,
	DATE_ACCOUNT				NVARCHAR(50)	NOT NULL,
	BALANCE						INT				NOT NULL
)

CREATE TABLE TRANSACTIONS
(
	TRAN_NUMBER					INT				NOT NULL PRIMARY KEY,
	ACCOUNT_NUMBER				INT,
	FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER),
	AMOUNT						INT				NOT NULL,
	DESCRIPTIONS				NVARCHAR(500)	NOT NULL
)

ALTER TABLE ACCOUNT 
ADD CUSTOMER_NUMBER INT
FOREIGN KEY (CUSTOMER_NUMBER) REFERENCES Customers(CUSTOMER_NUMBER)
