CREATE DATABASE StudentManagement

CREATE TABLE Student
(
	ID			INT				PRIMARY KEY,
	STDNAME		NVARCHAR(50),
	ADRESS		NVARCHAR(50),
	AGE			INT
)

INSERT INTO Student(ID,STDNAME,ADRESS,AGE) VALUES (1,N'NGUYÊN',N'HUẾ', 28)
INSERT INTO Student(ID,STDNAME,ADRESS,AGE) VALUES (2,N'HUY',N'HCM', 24)
INSERT INTO Student(ID,STDNAME,ADRESS,AGE) VALUES (3,N'LONG',N'ĐN', 23)
INSERT INTO Student(ID,STDNAME,ADRESS,AGE) VALUES (4,N'NAM',N'QTRI', 21)

SELECT * FROM Student

DELETE Student WHERE AGE > 21 AND AGE < 24   

UPDATE Student
SET STDNAME = N'CHINH', ADRESS = N'HUẾ', AGE = 25 WHERE ID = 4